(function(g){var window=this;'use strict';var W3=function(a){a.oa("cardstatechange",a.Dk()&&a.Uo()?1:0)},X3=function(a,b){var c=g.bb(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},glb=function(a){var b=g.us(a);
a=g.xs(a);return new g.is(b.x,b.y,a.width,a.height)},hlb=function(a,b,c){var d=void 0===d?{}:d;
var e;return e=g.cD(a,b,function(){g.dD(e);c.apply(a,arguments)},d)},$3=function(a){a=g.fb(a);
delete Y3[a];g.md(Y3)&&Z3&&Z3.stop()},jlb=function(){Z3||(Z3=new g.Tu(function(){ilb()},20));
var a=Z3;a.isActive()||a.start()},ilb=function(){var a=g.nb();
g.bd(Y3,function(b){klb(b,a)});
g.md(Y3)||jlb()},a4=function(a,b,c,d){g.rv.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.B=a;this.N=b;this.duration=c;this.G=d;this.coords=[];this.progress=this.K=0;this.D=null},klb=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.K=1E3/(b-a.D);a.D=b;llb(a,a.progress);1==a.progress?(a.j=0,$3(a),a.onFinish(),a.Yq()):a.isPlaying()&&a.hL()},llb=function(a,b){"function"===typeof a.G&&(b=a.G(b));
a.coords=Array(a.B.length);for(var c=0;c<a.B.length;c++)a.coords[c]=(a.N[c]-a.B[c])*b+a.B[c]},mlb=function(a,b){g.Ab.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.K;this.state=b.j},b4=function(a,b,c,d,e){a4.call(this,b,c,d,e);
this.element=a},nlb=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
b4.call(this,a,b,c,d,e)},olb=function(a){return Math.pow(a,3)},plb=function(a){return 3*a*a-2*a*a*a},qlb=function(a){g.I.call(this);
this.B=a||window;this.j=[]},c4=function(a){return a.baseUrl||null},d4=function(a,b){return g.rt(g.Fr(a,b),function(c){return!!c})},rlb=function(a,b,c){function d(na){var la=na.hovercardButton;
if(!la)return null;la=la.subscribeButtonRenderer;if(!la)return null;var pa=f(la.unsubscribedButtonText),ca=f(la.subscribedButtonText);if(la.subscribed){var W=f(la.subscriberCountWithUnsubscribeText);var Oa=f(la.subscriberCountText)}else W=f(la.subscriberCountText),Oa=f(la.subscriberCountWithSubscribeText);var y=null;if(na.signinEndpoint){y=X3(na,"signinEndpoint","webNavigationEndpointData","url");if(!y){var aa,Ta;y=null==(Ta=g.U(null==(aa=la.signInEndpoint)?void 0:aa.commandMetadata,g.P2))?void 0:
Ta.url}if(!y)return null}return pa&&(ca||y)?{subscribed:la.subscribed,subscribeText:pa,subscribeCount:W,unsubscribeText:ca,unsubscribeCount:Oa,enabled:la.enabled,signinUrl:y,classic:na.useClassicSubscribeButton}:null}
function e(na){if(na){var la=[],pa=na.videoId;pa&&la.push("v="+pa);(pa=na.playlistId)&&la.push("list="+pa);(na=na.startTimeSeconds)&&la.push("t="+na);return"/watch?"+la.join("&")}}
function f(na){if(!na)return null;var la=na.simpleText;return la?la:na.runs?g.Fr(na.runs,function(pa){return pa.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=!1,q=null,r=null,t=null,v=null,x=!1,B=null,E=null,F=null,H=null,P=null,Q=null;if("VIDEO"===h)g.U(l,g.TG)?m=g.U(l,g.TG).url:(Q=g.U(l,g.ET),m=e(Q)),n=!1,q=a,b.thumbnailOverlays?(p=b.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,r=f(p.text),p="LIVE"===p.style):r=f(b.videoDuration);else if("PLAYLIST"===h)g.U(l,g.TG)?m=g.U(l,g.TG).url:(Q=g.U(l,g.ET),m=e(Q)),n=!1,q=a,t=f(b.playlistLength);else if("CHANNEL"===
h){if(x=X3(l,"browseEndpoint","browseId"))v=x,m="/channel/"+v;n=!1;q="new";(x=!!b.isSubscribe)?B=d(b):E=f(b.subscribersText)}else"WEBSITE"===h?((F=X3(l,"urlEndpoint","url"))&&(m=F),n=!0,q="new",F=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(H=f(b.productPrice)),b.additionalFeesText&&(P=f(b.additionalFeesText)),(n=X3(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=X3(b,"title","accessibility","accessibilityData","label");var R=b.endpoint?b.endpoint.clickTrackingParams:null,
ha="";if(b.metadata){var ua=f(b.metadata);ua&&(ha=ua)}return{id:"element-"+c,type:h,title:f(b.title),metadata:ha,callToAction:f(b.callToAction),CV:b.image,iconUrl:F,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:r,KD:p,playlistLength:t,channelId:v,subscribeButton:B,subscribersText:E,isSubscribe:x,targetUrl:m||null,L7:n,sessionData:R?{itct:R}:null,gca:q,nC:a?a:null,isPlaceholder:b.isPlaceholder,
impressionUrls:d4(b.impressionUrls||[],c4),y7:d4(b.hovercardShowUrls||[],c4),clickUrls:d4(l.loggingUrls||[],c4),visualElement:g.SF(b.trackingParams),productPrice:H,additionalFeesText:P,watchEndpoint:Q||null}},slb=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:d4(a.impressionUrls||[],c4),elements:d4(a.elements||[],function(d,e){return rlb(b,d,e)})};
a.trackingParams&&(c.visualElement=g.SF(a.trackingParams));return c},tlb=function(a){g.YV.call(this,a);
this.C=this.endscreen=null;this.j={};this.G={};this.D=this.B=null;this.N=[];this.W=!0;this.K=0;a=a.U();this.Z=g.xS(a)||g.zS(a);this.events=new g.kL(this);g.M(this,this.events);this.events.T(this.player,g.yK("creatorendscreen"),this.onCueRangeEnter);this.events.T(this.player,g.zK("creatorendscreen"),this.onCueRangeExit);this.events.T(this.player,"resize",this.Xb);this.events.T(window,"focus",this.taa);this.load();var b=g.qf("STYLE");(g.We("HEAD")[0]||document.body).appendChild(b);this.addOnDisposeCallback(function(){g.vf(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},ulb=function(a){return a.player.getVideoData().Hf?"current":a.Z?"new":"current"},e4=function(a){return"creator-endscreen-editor"===a.player.U().playerStyle},vlb=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.C&&a.C.abort();c={method:"POST",onFinish:function(e){var f=a.C=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=slb(f,ulb(a))));f4(a,f)},
urlParams:{v:c},withCredentials:!0};a.Z&&(c.urlParams.ptype="embedded");var d=b.tx;d&&(c.postParams={ad_tracking:d});if(b=g.JSa(b))if(b=g.bo(b),b=g.de(b))a.C=g.uC(b,c)},f4=function(a,b,c){c=void 0===c?!0:c;
a.player.yf("creatorendscreen");a.B&&(a.B.dispose(),a.B=null,a.D.dispose(),a.D=null);for(var d=g.u(Object.values(a.j)),e=d.next();!e.done;e=d.next())e.value.dispose();a.j={};a.G={};0<a.N.length&&(a.N.forEach(function(l){l.dispose()}),a.N.length=0);
a.K=0;if((a.endscreen=b)&&b.elements){c&&wlb(a);c=[];d=new g.xK(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.U().B||(a.B=new g.V({I:"div",S:"ytp-ce-shadow"}),g.LU(a.player,a.B.element,4),a.D=new g.fH(a.B,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=xlb(a,e);if(f){a.j[e.id]=f;a.G[e.id]=e;g.LU(a.player,f.element,4);var h=new g.xK(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);ylb(a,f,e)}else g.YF(new g.tD("buildEndscreenElement null",
e))}a.player.sf(c);a.Xb()}},wlb=function(a){var b=g.TF(),c=g.UF();
c&&b&&a.endscreen.visualElement&&g.cC(g.mG)(void 0,c,b,a.endscreen.visualElement)},xlb=function(a,b){var c=null;
switch(b.type){case "VIDEO":a={I:"div",Ma:["ytp-ce-element","ytp-ce-video"],Y:{tabindex:"0","aria-label":b.nC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-covering-image",Y:g4(b)},{I:"div",S:"ytp-ce-covering-shadow-top"},{I:"a",S:"ytp-ce-covering-overlay",Y:{href:h4(a,b.targetUrl),tabindex:"-1"},V:[{I:"div",Ma:["ytp-ce-video-title","ytp-webkit-ellipsis"],Y:{dir:g.xv(b.title||"")},ya:b.title},{I:"div",S:b.KD?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
ya:b.videoDuration||void 0}]}]};c=new g.V(a);break;case "PLAYLIST":a={I:"div",Ma:["ytp-ce-element","ytp-ce-playlist"],Y:{tabindex:"0","aria-label":b.nC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-covering-image",Y:g4(b)},{I:"div",S:"ytp-ce-covering-shadow-top"},{I:"a",S:"ytp-ce-covering-overlay",Y:{href:h4(a,b.targetUrl),tabindex:"-1"},V:[{I:"div",Ma:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],Y:{dir:g.xv(b.title||"")},ya:b.title},{I:"div",S:"ytp-ce-playlist-count",
V:[{I:"div",S:"ytp-ce-playlist-icon"},{I:"div",S:"ytp-ce-playlist-count-text",ya:b.playlistLength||void 0}]}]}]};c=new g.V(a);break;case "CHANNEL":c={I:"div",Ma:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],Y:{tabindex:"0","aria-label":b.nC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",
V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"a",Ma:["ytp-ce-channel-title","ytp-ce-link"],Y:{href:h4(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.xv(b.title||"")},ya:b.title},b.subscribeButton?{I:"div",S:"ytp-ce-subscribe-container",V:[{I:"div",S:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{I:"div",S:"ytp-ce-channel-subscribers-text",ya:b.subscribersText}:"",b.metadata?{I:"div",Ma:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],ya:b.metadata}:""]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",Y:g4(b)}]};c=new g.V(c);var d=g.Xe(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.fv(d,"ytp-ce-subscribe-button");if(a.player.U().B){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.FW(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,
b.channelId,!!b.subscribeButton.subscribed,e,f,a.player,!1);d.appendChild(e.element);a.N.push(e)}break;case "WEBSITE":a={I:"div",Ma:["ytp-ce-element","ytp-ce-website"],Y:{tabindex:"0","aria-label":b.nC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",
S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"div",S:"ytp-ce-website-title",Y:{dir:g.xv(b.title||"")},ya:b.title},{I:"div",S:"ytp-ce-website-metadata",ya:b.metadata},{I:"a",Ma:["ytp-ce-website-goto","ytp-ce-link"],Y:{href:h4(a,b.targetUrl),target:"_blank",tabindex:"-1"},ya:b.callToAction}]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",Y:g4(b)},{I:"div",S:"ytp-ce-expanding-icon",Y:zlb(b.iconUrl)}]};c=new g.V(a);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={I:"div",S:"ytp-ce-merchandise-price-container",
V:[{I:"div",S:"ytp-ce-merchandise-price",ya:b.productPrice}]},b.additionalFeesText&&c.V.push({I:"div",S:"ytp-ce-merchandise-additional-fees",ya:b.additionalFeesText})),a={I:"div",Ma:["ytp-ce-element","ytp-ce-merchandise"],Y:{tabindex:"0","aria-label":b.nC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",
V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"div",S:"ytp-ce-merchandise-title",Y:{dir:g.xv(b.title||"")},ya:b.title},c,{I:"div",S:"ytp-ce-merchandise-metadata",ya:b.metadata},{I:"a",Ma:["ytp-ce-merchandise-goto","ytp-ce-link"],Y:{href:h4(a,b.targetUrl),target:"_blank",tabindex:"-1"},ya:b.callToAction}]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",Y:g4(b)},{I:"div",S:"ytp-ce-merchandise-invideo-cta-container",V:[{I:"div",S:"ytp-ce-merchandise-invideo-cta",
ya:b.callToAction||void 0}]}]},c=new g.V(a)}b.isPlaceholder&&g.fv(c.element,"ytp-ce-placeholder");return c},g4=function(a){if(a.CV)var b=a.CV.thumbnails;
return zlb(b?b[b.length-1].url:null)},zlb=function(a){return a?{style:"background-image: url("+a+")"}:{}},ylb=function(a,b,c){function d(m){m&&(b.Qa("blur",function(){"none"!=m.style.display&&a.W&&m.focus()}),b.T(m,"focus",f),b.T(m,"blur",h))}
function e(m){a.K+=m;0<a.K?(g.fv(b.element,"ytp-ce-force-expand"),i4(a,c.id,!0)):(g.hv(b.element,"ytp-ce-force-expand"),g.hv(b.element,"ytp-ce-element-hover"),i4(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.Qa("mouseenter",function(){Alb(a,b,c)});
b.Qa("mouseleave",function(){Blb(a,b,c)});
a.player.U().B||b.Qa("click",function(){g.fv(b.element,"ytp-ce-element-hover")});
b.Qa("click",function(m){Clb(a,c,m)});
b.Qa("keypress",function(m){Clb(a,c,m)});
b.Qa("focus",function(){Alb(a,b,c)});
b.Qa("blur",function(){Blb(a,b,c)});
b.Qa("touchstart",function(){Alb(a,b,c)});
var l=g.af("ytp-ce-expanding-overlay-hider",b.element);l&&b.T(l,"touchstart",function(m){m.stopPropagation();g.hv(b.element,"ytp-ce-element-hover");g.hv(b.element,"ytp-ce-force-expand")});
b.Qa("keydown",function(m){a.W=9===m.keyCode&&!m.shiftKey});
d(g.af("ytp-sb-subscribe",b.element));d(g.af("ytp-sb-unsubscribe",b.element));b.Qa("focus",f);b.Qa("blur",h)},Clb=function(a,b,c){if(b.targetUrl&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.$u(d,"ytp-ce-element");){g.$u(d,"subscribe-label")&&Dlb(a,b);
if(g.$u(d,"ytp-ce-channel-subscribe"))return;d=g.wf(d)}if(!d||g.$u(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.j[b.id])Blb(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.gca)Dlb(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.bo(h4(a,b.targetUrl)),g.HH(g.de(c),void 0,b.sessionData);else{var e=g.HS(a.player.U())||a.player.getVideoData().Hf,f=function(){var h=h4(a,b.targetUrl),l=b.sessionData,m=b.watchEndpoint,n=g.hC(h);e&&n&&(n.v||
n.list)?a.player.Ao(n.v,l,n.list,!1,void 0,m||void 0):g.Twa(h,l)};
Dlb(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},h4=function(a,b){a=a.player.U();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.OS(a)+b}else return"";return b},Alb=function(a,b,c){g.$u(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.fv(b.element,"ytp-ce-element-hover"):a.player.U().B?(new g.Tu(function(){g.fv(b.element,"ytp-ce-element-hover")},200)).start():g.fv(b.element,"ytp-ce-element-hover"),j4(a,c.y7),i4(a,c.id,!0))},Blb=function(a,b,c){g.hv(b.element,"ytp-ce-element-hover");
g.hv(b.element,"ytp-ce-force-expand");i4(a,c.id,!1)},i4=function(a,b,c){a.B&&(c?a.D.show():a.D.hide());
for(var d=g.u(Object.keys(a.j)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.jv(a.j[e].element,"ytp-ce-element-shadow-show",c)},j4=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||e4(a))c&&c();else{b=Elb(a,b);var e=0,f=!1,h=new g.Tu(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.NE(b[a],d)}},Dlb=function(a,b,c){j4(a,b.clickUrls,c);
(a=g.UF())&&b.L7&&g.tG(a,b.visualElement)},Elb=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(Flb(b[d],c));return a},Flb=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},Glb=function(a){return"string"===typeof a?a:""},k4=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},Hlb=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.j=d},l4=function(a){return a.value?a.value:null},m4=function(a){if(!a)return null;
var b=g.bo(Glb(a.value));b=g.de(b);if(!b)return null;var c=k4(a.target,Ilb,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new Hlb(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},Jlb=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},Mlb=function(a){if(!a)return null;
var b=k4(a.type,Klb),c=k4(a.trigger,Llb);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=m4(a?a:null);return b?new Jlb(b,c,a):null},Nlb=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},Olb=function(a,b){return g.Db(a.action,b)},Plb=function(a,b){this.context=a;
this.j=b},Qlb=function(a){return a.customMessage?n4("div","iv-card-message",a.customMessage):""},o4=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{I:"div",S:"iv-card-image",Y:{style:a},V:c}},Rlb=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.u(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(n4("li","",c.value));return{I:"ul",S:"iv-card-meta-info",V:b}},n4=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.xv(c);return{I:a,Y:b,ya:c}},Slb=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.wC&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.wC+");");c.dir=g.xv(a.customMessage);var d=[{I:"span",ya:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({I:"span",S:"iv-card-link-icon"}));return{I:"div",Ma:b,Y:c,V:d}},p4=function(a,b,c,d){if(d){b=g.u(b);
for(var e=b.next();!e.done;e=b.next())a.j(e.value,d,c.id,c.sessionData,c.cj.click,5)}},Tlb=function(a,b){this.merchant=a;
this.price=b},Ulb=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,"").split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},Vlb=function(a,b){return b?b:Ulb(a)?"current":"new"},q4=function(a,b){g.I.call(this);
var c=this;this.element=a;this.context=b;this.qb=!1;this.Xa=new Map;this.Za=new Map;this.context.J.addEventListener(g.yK("annotations_module"),function(d){(d=c.Xa.get(d))&&d.apply(c)});
this.context.J.addEventListener(g.zK("annotations_module"),function(d){(d=c.Za.get(d))&&d.apply(c)})},r4=function(a,b,c,d,e,f,h){a.context.j.Qa(b,"click",function(l){a.iL(c,d,e,f||[],h||0,l)});
a.context.j.Qa(b,"touchstart",function(){a.qb=!1});
a.context.j.Qa(b,"touchmove",function(){a.qb=!0})},Wlb=function(a){var b;
return(null==(b=g.U(a,g.TG))?0:b.url)?g.U(a,g.TG).url:(a=g.U(a,g.ET))&&a.videoId?(b="/watch?v="+a.videoId,a.playlistId&&(b+="&list="+a.playlistId),a.index&&(b+="&index="+a.index),a.startTimeSeconds&&(b+="&t="+a.startTimeSeconds),b):null},s4=function(a,b,c){return{gX:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
F_:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
xK:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},Xlb=function(a,b,c){q4.call(this,b,c);
var d=this;this.J=a;this.eventId=null;this.zb=this.Na=this.Rb=this.C=this.isInitialized=!1;this.cards=[];this.ub=this.Z=this.La=this.G=this.Ua=this.j=null;this.ma=[];this.ra=this.N=this.Ff=this.Ga=null;this.K=0;this.Ea=new g.Tu(function(){},c.X.vl?4E3:3E3);
g.M(this,this.Ea);this.ib=new g.Tu(function(){});
g.M(this,this.ib);this.Ba=new Plb(c,function(e,f,h,l,m,n){r4(d,e,f,h,l,m,n)});
this.W=new g.V({I:"div",S:"iv-drawer",Y:{id:"iv-drawer"},V:[{I:"div",S:"iv-drawer-header",Y:{"aria-role":"heading"},V:[{I:"span",S:"iv-drawer-header-text"},{I:"button",Ma:["iv-drawer-close-button","ytp-button"],Y:{"aria-label":"Ocultar tarjetas",tabindex:"0"}}]},{I:"div",S:"iv-drawer-content"}]});g.M(this,this.W);this.D=this.W.element;this.bb=new g.fH(this.W,330);g.M(this,this.bb);this.Ib=g.af("iv-drawer-header-text",this.D);this.B=g.af("iv-drawer-content",this.D);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.Rb&&t4(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Rb=d.C)&&u4(d)});
this.Ta=new g.kL(this);g.M(this,this.Ta);this.J.addEventListener("videodatachange",this.Ps.bind(this))},Ylb=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){t4(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){u4(a)});
var c=b.headerText;g.Bf(a.Ib,c);a.Z&&a.Z.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Ga=g.SF(b.trackingParams);a.N=g.SF(b.closeTrackingParams);a.Ff=g.SF(b.iconTrackingParams)},Zlb=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.K,d=a.J.U().experiments.kb("enable_error_corrections_infocard_web_client");
if(!b.content&&b.teaser.simpleCardTeaserRenderer&&d){var e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"simple",teaserText:g.HG(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:{},sponsored:!1,cj:{},Xo:null,Hj:e.trackingParams?g.SF(e.trackingParams):null,Ff:f&&f.trackingParams?g.SF(f.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,
wC:null,title:"",customMessage:"",url:null,onClickCommand:e.onTapCommand||null};v4(a,b)}else{var h;if(null==(h=b.content)?0:h.simpleCardContentRenderer){if(!b.cueRanges.length)return;f=null==(e=b.content)?void 0:e.simpleCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;var l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"simple",teaserText:g.HG(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,
sessionData:w4(a,c,b,f),sponsored:!1,cj:s4(f,e,f.command),Xo:f.trackingParams?g.SF(f.trackingParams):null,Hj:e.trackingParams?g.SF(e.trackingParams):null,Ff:l&&l.trackingParams?g.SF(l.trackingParams):null,imageUrl:x4(f.image.thumbnails,290).url,displayDomain:f.displayDomain?g.HG(f.displayDomain):null,showLinkIcon:!!f.showLinkIcon,wC:null,title:f.title?g.HG(f.title):"",customMessage:f.callToAction?g.HG(f.callToAction):"",url:g.U(f.command,g.TG).url?m4({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.U(f.command,g.TG).url}):null,onClickCommand:null};v4(a,b)}else{var m;if(null==(m=b.content)?0:m.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(f=b.content)?void 0:f.collaboratorInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"collaborator",teaserText:g.HG(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),
autoOpen:!!b.autoOpen,sessionData:w4(a,c,b,e),sponsored:!1,cj:s4(e,f,e.endpoint),Xo:e.trackingParams?g.SF(e.trackingParams):null,Hj:f.trackingParams?g.SF(f.trackingParams):null,Ff:l&&l.trackingParams?g.SF(l.trackingParams):null,channelId:g.U(e.endpoint,g.lV).browseId,customMessage:e.customText?g.HG(e.customText):null,profileImageUrl:x4(e.channelAvatar.thumbnails,290).url,title:e.channelName?g.HG(e.channelName):"",metaInfo:[e.subscriberCountText?g.HG(e.subscriberCountText):""],url:m4({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.U(e.endpoint,g.lV).canonicalBaseUrl?g.U(e.endpoint,g.lV).canonicalBaseUrl:"/channel/"+g.U(e.endpoint,g.lV).browseId}),onClickCommand:null};v4(a,b)}else{var n;if(null==(n=b.content)?0:n.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(l=b.content)?void 0:l.playlistInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"playlist",teaserText:g.HG(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:w4(a,c,b,e),sponsored:!1,cj:s4(e,f,e.action),Xo:e.trackingParams?g.SF(e.trackingParams):null,Hj:f.trackingParams?g.SF(f.trackingParams):null,Ff:l&&l.trackingParams?g.SF(l.trackingParams):null,IF:x4(e.playlistThumbnail.thumbnails,258).url,customMessage:e.customMessage?g.HG(e.customMessage):null,playlistVideoCount:g.HG(e.playlistVideoCount),title:e.playlistTitle?g.HG(e.playlistTitle):"",metaInfo:[e.channelName?g.HG(e.channelName):
"",e.videoCountText?g.HG(e.videoCountText):""],url:m4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:Wlb(e.action)}),onClickCommand:null};v4(a,b)}else{var p;if(null==(p=b.content)?0:p.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;var q;e=null==(q=b.content)?void 0:q.videoInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"video",teaserText:g.HG(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:w4(a,c,b,e),sponsored:!1,cj:s4(e,f,e.action),Xo:e.trackingParams?g.SF(e.trackingParams):null,Hj:f.trackingParams?g.SF(f.trackingParams):null,Ff:l&&l.trackingParams?g.SF(l.trackingParams):null,IF:x4(e.videoThumbnail.thumbnails,258).url,videoDuration:e.lengthString?g.HG(e.lengthString):null,customMessage:e.customMessage?g.HG(e.customMessage):null,title:e.videoTitle?g.HG(e.videoTitle):"",metaInfo:[e.channelName?g.HG(e.channelName):
"",e.viewCountText?g.HG(e.viewCountText):""],isLiveNow:!!e.badge,url:m4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:Wlb(e.action)}),onClickCommand:null};v4(a,b)}}}}}a.K++},x4=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},w4=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},amb=function(a,b){if(b=$lb(a,b))b===a.j&&(a.j=null),a.J.removeCueRange(b.dg.id),g.vf(b.BM),g.Ib(a.cards,b),a.HG(),y4(a)},t4=function(a,b,c){if(!a.C){a.bb.show();
a.Ua=new g.Tu(function(){g.fv(a.context.J.getRootNode(),g.jZ.IV_DRAWER_OPEN)},0);
a.Ua.start();a.Ta.T(a.B,"mousewheel",function(h){a.Ea.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.B.scrollTop+=h});
a.C=!0;var d=g.UF();d&&a.Ga&&a.N&&g.rG(d,[a.Ga,a.N]);b={TRIGGER_TYPE:b};for(var e=g.u(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.WX||(f.WX=!0,bmb(a.context.logger,f.dg.cj.gX,b)),d&&g.rG(d,[f.dg.Xo]);W3(a.J);c&&(a.G=new g.Tu(function(){a.La=a.Z;a.ub.focus()},330),a.G.start())}},u4=function(a){a.C&&(a.bb.hide(),g.iD(a.Ta),g.hv(a.context.J.getRootNode(),g.jZ.IV_DRAWER_OPEN),a.C=!1,W3(a.J),a.G&&a.G.stop(),a.G=new g.Tu(function(){a.La&&(a.La.focus(),a.La=null)},330),a.G.start())},dmb=function(a){g.gv(a.Jb(),
[g.jZ.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.LU(a.J,a.D,5);cmb(a);a.Z=g.af("ytp-cards-button",a.J.getRootNode());a.ub=g.af("iv-drawer-close-button",a.D);a.isInitialized=!0},cmb=function(a){var b=g.af("iv-drawer-close-button",a.D);
a.context.j.Qa(b,"click",a.n5,a);a.context.j.Qa(a.B,"touchend",function(){a.Ea.start()});
a.context.j.Qa(a.B,"scroll",a.J5,a);a.context.B.subscribe("onHideControls",function(){a.Na=!0});
a.context.B.subscribe("onShowControls",function(){a.Na=!1});
a.context.B.subscribe("onVideoAreaChange",function(){a.Na=g.$u(a.J.getRootNode(),"ytp-autohide")});
a.ma.push(g.aF("iv-button-shown",a.d8,a));a.ma.push(g.aF("iv-button-hidden",a.c8,a));emb(a)},emb=function(a){a.ma.push(g.aF("iv-teaser-shown",a.A1,a));
a.ma.push(g.aF("iv-teaser-hidden",a.e8,a));a.ma.push(g.aF("iv-teaser-clicked",a.z1,a));a.zb=!0},fmb=function(a,b){var c;
return b.onClickCommand&&"engagement-panel-error-corrections"===(null==(c=g.U(b.onClickCommand,g.Dhb))?void 0:c.targetId)?(a.ra=b,!0):!1},gmb=function(a,b){a.ra=b;
var c=a.J.getVideoData();if(!c)return!1;c=g.hRa(c);if(null==c?0:c.markersMap)for(var d,e=0;(null==(d=c)?void 0:d.markersMap.length)>e;e++){var f=void 0,h=null==(f=c)?void 0:f.markersMap[e];if("ERROR_CORRECTION_MARKERS"===h.key&&(f=void 0,(h=null==(f=h.value)?void 0:f.markers)&&0<h.length))return d=void 0,b.startMs=(null==(d=g.U(h[0],g.r_a))?void 0:d.timeRangeStartMillis)||0,a.ra=null,!0}return!1},v4=function(a,b){if(!fmb(a,b)||gmb(a,b)){var c=hmb(a,b);
if(c){var d={dg:b,BM:c.element,WX:!1};if(b.onClickCommand)a.J.L("web_infocards_teaser_show_logging_fix")&&(a.zb||emb(a),amb(a,b.id),c=a.findLastIndex(d),g.Pb(a.cards,c,0,d));else{a.isInitialized||dmb(a);amb(a,b.id);var e=a.findLastIndex(d);g.Pb(a.cards,e,0,d);c.Ja(a.B,e);a.HG()}b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.C||(a.j=d,y4(a),imb(a,d),t4(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.J.getCurrentTime(),5E3>c&&c>b.startMs&&jmb(a,d),a.addCueRange(b.startMs,
b.startMs+1,b.id,function(){jmb(a,d)}),y4(a))}}},hmb=function(a,b){switch(b.type){case "simple":a=a.Ba;
var c=b.displayDomain?{I:"div",S:"iv-card-image-text",ya:b.displayDomain}:void 0;var d=Slb(b);c={I:"div",Ma:["iv-card"],V:[{I:"a",S:"iv-click-target",Y:{href:b.url?l4(b.url)||"":""},V:[o4(b.imageUrl,c),{I:"div",S:"iv-card-content",V:[n4("h2",void 0,b.title),d]}]}]};c=new g.V(c);p4(a,g.Ye("iv-click-target",c.element),b,b.url);b=c;break;case "collaborator":a=a.Ba;c={I:"div",Ma:["iv-card","iv-card-channel"],V:[{I:"a",Ma:["iv-click-target"],Y:{href:l4(b.url)||"","data-ytid":b.channelId},V:[o4(b.profileImageUrl),
{I:"div",S:"iv-card-content",V:[Qlb(b),{I:"h2",S:"iv-card-primary-link",ya:b.title},Rlb(b)]}]}]};c=new g.V(c);p4(a,g.Ye("iv-click-target",c.element),b,b.url);b=c;break;case "playlist":a=a.Ba;c={I:"div",Ma:["iv-card","iv-card-playlist"],V:[{I:"a",S:"iv-click-target",Y:{href:l4(b.url)||""},V:[o4(b.IF,{I:"div",S:"iv-card-image-overlay",V:[{I:"span",S:"iv-card-playlist-video-count",ya:b.playlistVideoCount}]}),{I:"div",S:"iv-card-content",V:[Qlb(b),n4("h2","iv-card-primary-link",b.title),Rlb(b)]}]}]};
c=new g.V(c);p4(a,g.Ye("iv-click-target",c.element),b,b.url);b=c;break;case "productListing":a=a.Ba;var e=0!=b.offers.length;c=["iv-card"];d="";var f=Slb(b);e&&(c.push("iv-card-product-listing"),d="iv-card-primary-link",f=b.offers[0],e=[],f.price&&e.push({I:"div",S:"iv-card-offer-price",ya:f.price}),f.merchant&&e.push({I:"div",S:"iv-card-offer-merchant",ya:f.merchant}),f={I:"div",V:e});e=b.url?l4(b.url)||"":"";c={I:"div",Ma:c,Y:{tabindex:"0"},V:[{I:"a",Ma:["iv-card-image","iv-click-target"],Y:{style:"background-image: url("+
b.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{I:"div",S:"iv-card-content",V:[b.sponsored?{I:"div",S:"iv-card-sponsored",V:["Patrocinado",{I:"div",S:"iv-ad-info-container",V:[{I:"div",S:"iv-ad-info",ya:"{{adInfo}}"},{I:"div",S:"iv-ad-info-icon-container",V:[{I:"div",S:"iv-ad-info-icon"},{I:"div",S:"iv-ad-info-callout"}]}]}]}:"",{I:"a",S:"iv-click-target",Y:{href:e},V:[n4("h2",d,b.title),f]}]}]};c=new g.V(c);d=g.qf("span");g.Bf(d,"Est\u00e1s viendo este producto porque creemos que es relevante para el v\u00eddeo. Es posible que Google reciba una compensaci\u00f3n de parte del comerciante.");
c.Zd(d,"adInfo");p4(a,g.Ye("iv-click-target",c.element),b,b.url);b=c;break;case "video":a=a.Ba;d=b.videoDuration?{I:"span",S:"iv-card-video-duration",ya:b.videoDuration}:void 0;f=b.isLiveNow?{I:"span",Ma:["yt-badge","yt-badge-live"],ya:"EN DIRECTO AHORA"}:null;e={I:"div",Ma:["iv-card","iv-card-video"],V:[{I:"a",S:"iv-click-target",Y:{href:(null==(c=b.url)?void 0:l4(c))||""},V:[o4(b.IF,d),{I:"div",S:"iv-card-content",V:[Qlb(b),n4("h2","iv-card-primary-link",b.title),Rlb(b),f]}]}]};c=new g.V(e);p4(a,
g.Ye("iv-click-target",c.element),b,b.url);b=c;break;default:return null}return b},kmb=function(a){if(a.j)return"productListing"===a.j.dg.type;
if(a.J.L("enable_wn_infocards")){var b;return!(null==(b=a.cards)||!b.length)&&g.Gr(a.cards,function(c){return"productListing"===c.dg.type})}return g.Gr(a.cards,function(c){return"productListing"===c.dg.type})},y4=function(a){g.jv(a.J.getRootNode(),"ytp-cards-shopping-active",kmb(a))},jmb=function(a,b){if(!g.$u(a.J.getRootNode(),"ytp-cards-teaser-shown")){if(a.j!==b){var c=g.UF(),d=a.j?a.j.dg.Ff:a.Ff;
c&&d&&g.sG(c,[d]);a.j=b;y4(a)}(c=a.isInitialized&&"none"==a.Jb().style.display)||(c=a.context.J.getPlayerState(),d=0===c&&0===a.context.J.getCurrentTime(),c=!(1===c||3===c||d));c||b.dg.teaserDurationMs&&a.J.VA(!0,{teaserText:b.dg.teaserText,durationMs:b.dg.teaserDurationMs,onClickCommand:b.dg.onClickCommand});a.ib.isActive()||((!a.C||!a.Ea.isActive()&&a.Na)&&imb(a,b),a.ib.start(910+b.dg.teaserDurationMs))}},imb=function(a,b){a.W.Hb?(b=new a4([0,
a.B.scrollTop],[0,b.BM.offsetTop],600,plb),a.context.C.Qa(b,"animate",function(c){a.B.scrollTop=c.y}),a.context.C.Qa(b,"finish",function(c){a.B.scrollTop=c.y}),b.play()):(g.DG(a.W,!0),a.B.scrollTop=b.BM.offsetTop,g.DG(a.W,!1))},z4=function(a){return a.j&&a.j.dg?a.j.dg:a.cards[0]&&a.cards[0].dg?a.cards[0].dg:null},$lb=function(a,b){return g.Db(a.cards,function(c){return c.dg.id===b})},A4=function(a,b,c){q4.call(this,a,b);
this.annotation=c;this.isActive=!1},lmb=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},B4=function(a,b,c){A4.call(this,a,b,c);
this.B=null;this.N=!1;this.C=null;this.D=!1;this.j=this.K=this.G=null},mmb=function(a,b){var c=void 0===c?0:c;
var d=glb(b).width;g.rs(b,d);c=new nlb(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,olb);g.M(a,c);a.context.C.Qa(c,"begin",function(){g.ys(b,!0)});
c.play()},pmb=function(a,b){if(b.channel_name){var c=a.createElement({I:"div",
Ma:["iv-branding-context-name"],ya:b.channel_name}),d=a.createElement({I:"div",Ma:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.j=new g.FW(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,a.context.J,!1),a.j.Ja(d));var f=a.createElement({I:"div",Ma:["iv-branding-context-subscribe-caret"]}),h=a.createElement({I:"div",Ma:["branding-context-container-inner"]});h.appendChild(f);
h.appendChild(c);h.appendChild(d);g.ys(h,!1);var l=a.createElement({I:"div",Ma:["branding-context-container-outer"]});l.appendChild(h);g.ls(l,"right",b.image_width+"px");g.sf(a.Jb(),l);a.C=new g.Tu(function(){nmb(a,h,l)},500);
g.M(a,a.C);a.context.j.Qa(a.Jb(),"mouseover",function(){omb(a,h,l,f,b.image_height)});
a.context.j.Qa(a.Jb(),"mouseout",function(){a.C.start()})}},omb=function(a,b,c,d,e){a.C.stop();
if(!a.D){var f=g.xs(b);a.j||(b.style.width=g.qs(f.width,!0),c.style.width=g.qs(f.width,!0));g.ls(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.ls(d,"right","1px");a.D=!0;g.ys(b,!0);a.G=new g.Tu(function(){g.fv(this.Jb(),"iv-branding-active")},0,a);
a.G.start()}},nmb=function(a,b,c){g.hv(a.Jb(),"iv-branding-active");
a.K=new g.Tu(function(){g.ys(b,!1);a.j||(c.style.width=g.qs(0,!0))},250);
a.K.start();a.D=!1},qmb=function(a,b,c,d,e,f,h){this.j=a;
this.C=b;this.X=c;this.videoData=d;this.logger=e;this.J=f;this.B=h},rmb=function(a,b,c){A4.call(this,a,b,c);
var d=this;this.Z=this.isCollapsed=this.W=!1;this.K=5E3;this.B=this.C=this.j=this.D=null;this.N=this.createElement({I:"div",Ma:["iv-promo-contents"]});this.G=new g.Tu(function(){d.j.setAttribute("aria-hidden","true");g.ys(d.C,!1);g.ys(d.B,!0)},700,this);
g.M(this,this.G)},umb=function(a,b,c){c.stopPropagation();
smb(a);tmb(a,b);a.j.focus()},vmb=function(a){a.isCollapsed||a.Z||a.D||(g.fv(a.Jb(),"iv-promo-collapsed"),a.isCollapsed=!0,a.G.start())},smb=function(a){a.G.stop();
a.isCollapsed&&(g.iv(a.Jb(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.j&&a.j.removeAttribute("aria-hidden"),g.ys(a.B,!1),g.ys(a.C,!0))},tmb=function(a,b){a.D||(a.D=g.gg(function(){wmb(this);
vmb(this)},b,a))},wmb=function(a){a.D&&(g.Sa.clearTimeout(a.D),a.D=null)},xmb=function(a){this.J=a},bmb=function(a,b,c){b&&(c?C4(a,b.map(function(d){return g.Iu(d,c)})):C4(a,b))},C4=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.u(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.NE(m,f);d&&(e++,0!==d&&a.J.sendVideoStatsEngageEvent(d,f))},ymb=function(a){g.YV.call(this,a);
var b=this;this.ma=this.Z=!1;this.loadNumber=0;this.N={};this.logger=new xmb(this.player);this.D=new g.kL(this);this.G=this.K=null;this.events=new g.kL(this);this.Rg=this.W=this.j=null;this.ra=[];g.M(this,this.D);this.D.T(this.player,"onVideoAreaChange",function(){b.oa("onVideoAreaChange")});
this.D.T(this.player,"onHideControls",function(){b.oa("onHideControls")});
this.D.T(this.player,"onShowControls",function(){b.oa("onShowControls")});
this.D.T(this.player,"resize",function(d){b.oa("resize",d)});
this.D.T(this.player,"presentingplayerstatechange",function(d){b.oa("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.B1,this);this.subscribe("resize",this.mJ,this);this.player.U().Na.subscribe("vast_info_card_add",this.eZ,this);g.M(this,this.events);this.Ba=this.createElement({I:"div",S:"video-custom-annotations"});this.B=new g.V({I:"div",Ma:["ytp-player-content","ytp-iv-player-content"]});g.M(this,this.B);g.LU(this.player,this.B.element,4);this.B.hide();this.C=new g.V({I:"div",Ma:["ytp-iv-video-content"]});g.M(this,this.C);a=this.createElement({I:"div",S:"video-annotations"});
a.appendChild(this.Ba);this.C.element.appendChild(a);this.Rt()&&this.load();var c=this.createElement({I:"style"});(g.We("HEAD")[0]||document.body).appendChild(c);this.addOnDisposeCallback(function(){g.vf(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},zmb=function(a){a=a.createElement({I:"div",
Ma:["annotation","annotation-type-custom"]});g.ys(a,!1);return a},Amb=function(a,b){b=!b.isCued()&&!g.mH(b,1024);
g.DG(a.B,b);g.DG(a.C,b)},Bmb=function(a,b,c){a.Z=!0;
a.G=g.uC(b,c)},Cmb=function(a,b){for(var c={},d=g.u(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.cb(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(Cmb(a,e))}return c},Gmb=function(a){var b=a.player.getVideoData();
if(b.Xa){var c=a.player.U().Na.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=a.loadNumber;f=b.videoId;a.loaded&&a.loadNumber===e&&a.player.getVideoData().videoId===f&&(h=g.oC(h)&&h.responseXML?h.responseXML:null)&&Dmb(a,h)}};
g.BD()&&(d.onFinish=Emb(a,d.onFinish));d.postParams={ic_only:"1"};Fmb(d,c);a.Z=!0;g.uC(b.Xa,d)}}},Fmb=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.MG&&(a.postParams.ic_coll=b.MG);b.CM&&(a.postParams.ic_xml=b.CM);b.CK&&(a.postParams.ic_track=b.CK)},Hmb=function(a){var b=new g.V({I:"div"});
g.ys(b.element,!1);var c=new Xlb(a.player,b.element,D4(a));g.M(c,b);b.Ja(a.B.element);c.vF();return c},Jmb=function(a,b){var c,d;
if(b=null==(c=b.getWatchNextResponse())?void 0:null==(d=c.cards)?void 0:d.cardCollectionRenderer)a.ma=!0,Imb(a,b),b.headerText&&a.Rg&&(c=g.HG(b.headerText),a.Rg.setAttribute("title",c))},D4=function(a){if(!a.W){var b=new qlb(a);
g.M(a,b);var c=new g.Cp(a);g.M(a,c);a.W=new qmb(b,c,a.player.U(),a.player.getVideoData(),a.logger,a.player,a.rj)}return a.W},Dmb=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.UF();if(e){var f=g.TF();f&&g.cC(g.tva)(void 0,e,f,[g.SF(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=Cmb(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m="string"===typeof h&&null!=l&&null!=h&&h.match(l)?h:"";var n=k4(f.type,Kmb),p=k4(f.style,Lmb),q=Glb(f.data),r=0!==q.length?JSON.parse(q):{};var t=f.action;f=Mlb;if(null==t)var v=null;else if(g.bb(t)){l=[];for(var x=g.u(t),B=x.next();!B.done;B=x.next()){var E=f(B.value);
E&&l.push(E)}v=l}else{var F=f(t);v=F?[F]:[]}e=m&&n?new Nlb(m,n,p,v,r):null}else e=null}catch(ua){}if(e)if("branding"===e.type||"promotion"===e.type){f=a;l=e;var H=zmb(f),P=null;switch(l.type){case "branding":if(f.player.U().ze)break;f.B.element.appendChild(H);P=new B4(H,D4(f),l);break;case "promotion":g.LU(f.player,H,4),P=new rmb(H,D4(f),l)}P&&P.vF();if(f=P)g.M(a,f),a.N[e.id]=f}else if("card"===e.type||"drawer"===e.type){a.j||(a.j=Hmb(a),g.M(a,a.j));if("card"===e.type){H=a.j;var Q=(c=e)&&c.data&&
c.data.card_type;e=c.data;if(Q)switch(f=e.tracking||{},f={gX:f.impression,click:f.click,close:f.close,F_:f.teaser_impression,xK:f.teaser_click},l=e.tracking_params||{},P=null,Q){case "collaborator":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,cj:f,Xo:l.card?g.SF(l.card):null,Hj:l.teaser?g.SF(l.teaser):null,Ff:l.icon?g.SF(l.icon):
null,channelId:e.channel_id,customMessage:e.custom_message?e.custom_message:null,profileImageUrl:e.image_url,title:e.title,metaInfo:e.meta_info,url:m4({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};v4(H,c);break;case "playlist":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,cj:f,
Xo:l.card?g.SF(l.card):null,Hj:l.teaser?g.SF(l.teaser):null,Ff:l.icon?g.SF(l.icon):null,IF:e.image_url,playlistVideoCount:e.playlist_video_count,customMessage:e.custom_message?e.custom_message:null,title:e.title,metaInfo:e.meta_info,url:m4({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};v4(H,c);break;case "productListing":e.signin_url&&(P=m4({target:"current",value:e.signin_url}));Q=[];for(var R=e.offers||[],ha=0;ha<R.length;ha++)Q.push(new Tlb(g.Ne(R[ha].merchant),
g.Ne(R[ha].price)));c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,cj:f,Xo:l.card?g.SF(l.card):null,Hj:l.teaser?g.SF(l.teaser):null,Ff:l.icon?g.SF(l.icon):null,imageUrl:e.image_url,displayDomain:e.display_domain?e.display_domain:null,showLinkIcon:!!e.show_link_icon,wC:e.button_icon_url?e.button_icon_url:null,title:e.title,customMessage:e.custom_message?
e.custom_message:null,url:m4({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),Vmb:P,Umb:e.signin_title?e.signin_title:void 0,Tmb:e.signin_message?e.signin_message:void 0,offers:Q,onClickCommand:null};v4(H,c);break;case "simple":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,cj:f,Xo:l.card?g.SF(l.card):
null,Hj:l.teaser?g.SF(l.teaser):null,Ff:l.icon?g.SF(l.icon):null,imageUrl:e.image_url,displayDomain:e.display_domain?e.display_domain:null,showLinkIcon:!!e.show_link_icon,wC:e.button_icon_url?e.button_icon_url:null,title:e.title,customMessage:e.custom_message?e.custom_message:null,url:m4({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};v4(H,c);break;case "video":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,
startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,cj:f,Xo:l.card?g.SF(l.card):null,Hj:l.teaser?g.SF(l.teaser):null,Ff:l.icon?g.SF(l.icon):null,IF:e.image_url,videoDuration:e.video_duration||null,customMessage:e.custom_message?e.custom_message:null,title:e.title,metaInfo:e.meta_info,isLiveNow:!!e.is_live_now,url:m4({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null},v4(H,c)}}else Ylb(a.j,e);c=!0}}c&&
(W3(a.player),a.mJ())},Imb=function(a,b){var c=!1;
a.j||(a.j=Hmb(a),g.M(a,a.j));for(var d=g.u(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(Zlb(a.j,e.cardRenderer),c=!0);if(c){var f;null!=(f=a.player.getVideoData())&&g.$T(f)||(c=a.j,d=b.headerText?g.HG(b.headerText):"",g.Bf(c.Ib,d),c.Z&&c.Z.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Ga=b.trackingParams?g.SF(b.trackingParams):null,c.N=b.closeButton.infoCardIconRenderer.trackingParams?g.SF(b.closeButton.infoCardIconRenderer.trackingParams):
null,c.Ff=b.icon.infoCardIconRenderer.trackingParams?g.SF(b.icon.infoCardIconRenderer.trackingParams):null,a.mJ());W3(a.player)}},Mmb=function(a,b,c,d,e){if(!a.player.U().ze){var f=[];
b.navigationEndpoint&&g.U(b.navigationEndpoint,g.lV)&&g.U(b.navigationEndpoint,g.lV).browseId&&f.push(new Jlb("openUrl","click",new Hlb("/channel/"+g.U(b.navigationEndpoint,g.lV).browseId,"new",!0,!0)));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&g.U(b.subscribeButton,
g.ST)){d.channel_id=g.U(b.subscribeButton,g.ST).channelId;var l;b=g.U(b.subscribeButton,g.ST);h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.HG(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.HG(b.subscriberCountText))):(b.subscriberCountText&&(e=g.HG(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.HG(b.subscriberCountWithSubscribeText)));var m,n=(null==(m=g.U(null==(l=b.signInEndpoint)?void 0:l.commandMetadata,g.P2))?void 0:m.url)||"";l={subscribeText:g.HG(b.unsubscribedButtonText),
subscribeCount:e||"",unsubscribeText:g.HG(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:n};d.standalone_subscribe_button_data=l}f=new Nlb(c,"branding","branding",f,d);l=zmb(a);a.B.element.appendChild(l);f=new B4(l,D4(a),f);f.vF();g.M(f,f);a.N[c]=f}},Emb=function(a,b){return function(){var c=g.Ia.apply(0,arguments);
a.isDisposed()||a.ra.push(g.Lu.Ri(function(){b.apply(null,g.qa(c))}))}},Nmb=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.DU.prototype.VA=g.ea(29,function(a,b){var c=g.nW(this.Cb());c&&c.VA(a,b)});
var Y3={},Z3=null;g.ob(a4,g.rv);g.k=a4.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.j)this.progress=0,this.coords=this.B;else if(this.isPlaying())return!1;$3(this);this.startTime=a=g.nb();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.eJ();this.Sl("play");this.isPaused()&&this.Sl("resume");this.j=1;var b=g.fb(this);b in Y3||(Y3[b]=this);jlb();klb(this,a);return!0};
g.k.stop=function(a){$3(this);this.j=0;a&&(this.progress=1);llb(this,this.progress);this.Sl("stop");this.Yq()};
g.k.pause=function(){this.isPlaying()&&($3(this),this.j=-1,this.Sl("pause"))};
g.k.xa=function(){0==this.j||this.stop(!1);this.Sl("destroy");a4.Lf.xa.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.hL=function(){this.Sl("animate")};
g.k.Sl=function(a){this.dispatchEvent(new mlb(a,this))};
g.ob(mlb,g.Ab);g.ob(b4,a4);b4.prototype.C=function(){};
b4.prototype.hL=function(){this.C();b4.Lf.hL.call(this)};
b4.prototype.Yq=function(){this.C();b4.Lf.Yq.call(this)};
b4.prototype.eJ=function(){this.C();b4.Lf.eJ.call(this)};
g.ob(nlb,b4);nlb.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.w(qlb,g.I);g.k=qlb.prototype;g.k.Qa=function(a,b,c,d){c=(0,g.jb)(c,d||this.B);a=g.cD(a,b,c);this.j.push(a);return a};
g.k.FI=function(a,b,c,d){c=(0,g.jb)(c,d||this.B);a=hlb(a,b,c);this.j.push(a);return a};
g.k.Pc=function(a){g.dD(a);g.Ib(this.j,a)};
g.k.Jf=function(){g.dD(this.j);this.j.length=0};
g.k.xa=function(){this.Jf();g.I.prototype.xa.call(this)};g.w(tlb,g.YV);g.k=tlb.prototype;g.k.load=function(){g.YV.prototype.load.call(this);if(!e4(this)){var a=g.KSa(this.player.getVideoData());a?(a=slb(a,ulb(this)),f4(this,a,!1)):vlb(this)}};
g.k.unload=function(){f4(this,null);this.C&&(this.C.abort(),this.C=null);g.YV.prototype.unload.call(this)};
g.k.Fh=function(a,b){return e4(this)?"loadCustomEndscreenRenderer"===a?(a=slb(b,"new"),f4(this,a),!0):null:null};
g.k.getOptions=function(){return e4(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.Xb=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<Omb.length;f++){var h=Math.abs(b.width-Omb[f]);if(-1===e||d>=h)e=f,d=h}d=Pmb[e];this.B&&g.ls(this.B.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.j[f],
h=this.G[f],e&&h){var l=h.width*c/h.aspectRatio,m=Math.round(h.width*a.width);f=Math.round(l*a.height);var n=a.left+Math.round(h.left*a.width),p=a.top+Math.round(h.top*a.height);g.ws(e.element,m,f);g.rs(e.element,n,p);g.iv(e.element,Qmb);256<m||256<f?g.fv(e.element,"ytp-ce-large-round"):96<m||96<f?g.fv(e.element,"ytp-ce-medium-round"):g.fv(e.element,"ytp-ce-small-round");g.iv(e.element,Rmb);m=h.left+h.width/2;h=h.top+l/2;g.fv(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":
.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.iv(e.element,Pmb);g.fv(e.element,d);(e=g.Xe(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.ls(e,"height",f+"px")}}}}};
g.k.onCueRangeEnter=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())j4(this,this.endscreen.impressionUrls),(a=g.UF())&&this.endscreen.visualElement&&g.qG(a,this.endscreen.visualElement);else{a=a.getId().substring(15);var b=this.j[a],c=this.G[a];g.fv(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.fv(b,"ytp-ce-shown");j4(this,c.impressionUrls);(b=g.UF())&&g.qG(b,c.visualElement);this.player.U().K&&this.player.jb("endscreenelementshown",
a)}};
g.k.onCueRangeExit=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.j[a];g.hv(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.hv(b,"ytp-ce-shown");this.player.U().K&&this.player.jb("endscreenelementhidden",a)}};
g.k.taa=function(a){var b=this;a.target===window&&(new g.Tu(function(){for(var c=g.u(Object.values(b.j)),d=c.next();!d.done;d=c.next())g.iv(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var Omb=[346,426,470,506,570,640,853,1280,1920],Pmb="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),Rmb=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],Qmb=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var Ilb={Bta:"current",dUa:"new"};var Klb={CLOSE:"close",SXa:"openUrl",SUBSCRIBE:"subscribe"},Llb={Kra:"click",CLOSE:"close",nFa:"hidden",K2a:"rollOut",L2a:"rollOver",t4a:"shown"};Nlb.prototype.gf=function(){var a=Olb(this,function(b){return"openUrl"===b.type&&null!=b.url});
return a?a.url:null};
var Lmb={rma:"anchored",P0:"branding",CHANNEL:"channel",rta:"cta",qFa:"highlightText",rJa:"label",PLAYLIST:"playlist",z_a:"popup",s7a:"speech",SUBSCRIBE:"subscribe",aab:"title",VIDEO:"video",Ihb:"website"},Kmb={P0:"branding",xpa:"card",Fva:"drawer",pFa:"highlight",BPa:"marker",f1a:"promotion",TEXT:"text",ljb:"widget"};g.w(q4,g.I);g.k=q4.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.xK(a,b,{id:c,namespace:"annotations_module"});d&&this.Xa.set(a,d);e&&this.Za.set(a,e);this.context.J.sf([a])};
g.k.vF=function(){this.context.B.subscribe("resize",this.HG,this)};
g.k.Jb=function(){return this.element};
g.k.iL=function(a,b,c,d,e,f){if(this.qb)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.vf(this.Jb())};
g.k.HG=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=l4(a);if(f){var h=Vlb(f,a.target),l=function(){a.j&&e.context.J.pauseVideo();var m=e.context.videoData.Hf||!1,n=g.hC(f||"");m&&n&&(n.v||n.list)?e.context.J.Ao(n.v,b,n.list,!1):g.HH(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);C4(this.context.logger,c,l,d);Ulb(f)||(c=g.UF(),d=b.itct,c&&d&&g.tG(c,g.SF(d)))}};
g.k.xa=function(){this.Xa.clear();this.Za.clear();g.I.prototype.xa.call(this)};
g.k.createElement=function(a){a=new g.V(a);g.M(this,a);return a.element};g.w(Xlb,q4);g.k=Xlb.prototype;g.k.Ps=function(){this.ra&&v4(this,this.ra)};
g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.J.getRootNode())?(a=g.xs(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.HG=function(){var a=this.isAvailable();g.ys(this.Jb(),a);g.jv(this.context.J.getRootNode(),g.jZ.IV_DRAWER_ENABLED,a);W3(this.J)};
g.k.destroy=function(){this.J.VA(!1);try{this.J.getRootNode().removeChild(this.D)}catch(a){}g.bF(this.ma);g.iD(this.Ta);this.Ua&&this.Ua.dispose();this.G&&this.G.dispose();q4.prototype.destroy.call(this)};
g.k.findLastIndex=function(a){if(0===this.cards.length)return 0;var b=g.Eb(this.cards,function(c){return a.dg.startMs>c.dg.startMs||a.dg.startMs===c.dg.startMs&&a.dg.timestamp>=c.dg.timestamp?!0:!1});
return-1===b?0:b+1};
g.k.n5=function(){if(this.C){C4(this.context.logger,z4(this).cj.close);var a=g.UF();a&&this.N&&g.tG(a,this.N);u4(this)}};
g.k.J5=function(){g.jv(this.D,"iv-drawer-scrolled",0<this.B.scrollTop)};
g.k.d8=function(){var a=g.UF(),b=z4(this);b=b?b.Ff:this.Ff;a&&b&&g.rG(a,[b])};
g.k.c8=function(){var a=g.UF(),b=z4(this);b=b?b.Ff:this.Ff;a&&b&&g.sG(a,[b])};
g.k.A1=function(){var a=z4(this);C4(this.context.logger,a.cj.F_);var b=g.UF();if(b&&a)if(this.J.L("web_infocards_teaser_show_logging_fix")){var c=[];a.Hj&&c.push(a.Hj);a.Ff&&c.push(a.Ff);0<c.length&&g.rG(b,c)}else g.rG(b,[a.Hj,a.Ff])};
g.k.e8=function(){var a=g.UF(),b=z4(this);a&&b&&g.sG(a,[b.Hj])};
g.k.z1=function(a){var b=z4(this),c=g.UF();this.j?a?(a=this.context.logger,C4(a,b.cj.xK),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.Hj&&g.tG(c,b.Hj)):(a=this.context.logger,C4(a,b.cj.xK),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.Ff&&g.tG(c,b.Ff)):(a=this.context.logger,C4(a,b.cj.xK),a.J.sendVideoStatsEngageEvent(4,void 0),c&&this.Ff&&g.tG(c,this.Ff))};g.w(A4,q4);A4.prototype.vF=function(){q4.prototype.vF.call(this);lmb(this)};
A4.prototype.show=function(){q4.prototype.show.call(this);var a=g.UF(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.rG(a,[g.SF(b.itct)])};
A4.prototype.hide=function(){q4.prototype.hide.call(this);var a=g.UF(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.sG(a,[g.SF(b.itct)])};g.w(B4,A4);
B4.prototype.MA=function(){g.fv(this.Jb(),"iv-branding");var a=this.annotation.data;this.B=this.createElement({I:"img",Ma:["branding-img","iv-click-target"],Y:{"aria-label":"Marca de agua del canal",src:a.image_url,width:a.image_width,height:a.image_height}});g.ys(this.B,!1);var b=this.createElement({I:"button",Ma:["branding-img-container","ytp-button"]});b.appendChild(this.B);this.Jb().appendChild(b);var c=this.annotation.gf();c&&r4(this,b,c,this.annotation.id,a.session_data);pmb(this,a)};
B4.prototype.show=function(){if(!this.isActive&&(A4.prototype.show.call(this),this.N||(this.MA(),this.N=!0),g.ys(this.Jb(),!0),this.isActive=!0,this.B)){try{mmb(this,this.B)}catch(a){}g.fv(this.context.J.getRootNode(),"ytp-branding-shown")}};
B4.prototype.hide=function(){this.isActive&&(A4.prototype.hide.call(this),g.ys(this.Jb(),!1),this.isActive=!1,g.hv(this.context.J.getRootNode(),"ytp-branding-shown"))};
B4.prototype.destroy=function(){this.j&&(this.j.dispose(),this.j=null);A4.prototype.destroy.call(this)};g.w(rmb,A4);g.k=rmb.prototype;
g.k.MA=function(){var a=this,b=this.annotation.data;if("cta"===this.annotation.style)var c=6;else if("video"===this.annotation.style||"playlist"===this.annotation.style)c=7;this.K=b.collapsedelay_ms||this.K;var d=["iv-promo","iv-promo-inactive"];this.Jb().setAttribute("aria-hidden","true");this.Jb().setAttribute("aria-label","Promoci\u00f3n");this.Jb().tabIndex=0;var e=this.annotation.gf(),f=b.image_url;if(f){var h=this.createElement({I:"div",Ma:["iv-promo-img","iv-click-target"]});f=this.createElement({I:"img",
Y:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&!b.is_live?(f=this.createElement({I:"span",S:"iv-promo-video-duration",ya:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=this.createElement({I:"span",S:"iv-promo-playlist-length",ya:b.playlist_length.toString()}),h.appendChild(f));e&&r4(this,h,e,this.annotation.id,b.session_data,void 0,c)}e?(f=this.createElement({I:"a",S:"iv-promo-txt"}),g.fo(f,l4(e)),this.j=f):this.j=this.createElement({I:"div",S:"iv-promo-txt"});switch(this.annotation.style){case "cta":case "website":var l=
this.createElement({I:"p",V:[{I:"strong",ya:b.text_line_1}]});var m=this.createElement({I:"p",V:[{I:"span",S:"iv-promo-link",ya:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=this.createElement({I:"button",Ma:["iv-promo-round-expand-icon","ytp-button"]});f=this.createElement({I:"button",Ma:["iv-button","iv-promo-button"],V:[{I:"span",S:"iv-button-content",ya:f}]});var p=this.createElement({I:"div",S:"iv-promo-button-container"});p.appendChild(f);e&&r4(this,
this.Jb(),e,this.annotation.id,b.session_data,void 0,c)}g.fv(this.j,"iv-click-target");e&&r4(this,this.j,e,this.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=this.createElement({I:"p",V:[{I:"span",ya:b.text_line_1}]}),m=this.createElement({I:"p",V:[{I:"strong",ya:b.text_line_2}]}),b.is_live&&(l=m,m=this.createElement({I:"span",Ma:["yt-badge","iv-promo-badge-live"],ya:"EN DIRECTO AHORA"})),g.fv(this.j,"iv-click-target"),e&&r4(this,this.j,e,this.annotation.id,b.session_data,
void 0,c),d.push("iv-promo-video")}l&&this.j.appendChild(l);m&&this.j.appendChild(m);this.N.appendChild(this.j);p&&this.N.appendChild(p);c=this.createElement({I:"div",S:"iv-promo-actions"});this.B=this.createElement({I:"button",Ma:["iv-promo-expand","ytp-button"]});this.B.title="Expandir";this.context.j.Qa(this.B,"click",function(q){umb(a,5E3,q)});
c.appendChild(this.B);g.ys(this.B,!1);this.context.j.Qa(this.Jb(),"mouseover",this.Z6,this);this.context.j.Qa(this.Jb(),"mouseout",this.Y6,this);this.context.j.Qa(this.Jb(),"touchend",function(q){umb(a,5E3,q)});
this.C=this.createElement({I:"button",Ma:["iv-promo-close","ytp-button"]});this.C.title="Cerrar";this.context.j.Qa(this.C,"click","cta"===this.annotation.style&&b.text_line_3?this.U6:this.T6,this);c.appendChild(this.C);g.gv(this.Jb(),d);h&&(g.sf(this.Jb(),h),n&&h.appendChild(n));g.sf(this.Jb(),this.N);g.sf(this.Jb(),c)};
g.k.show=function(){this.isActive||(A4.prototype.show.call(this),this.W||(this.MA(),this.W=!0),g.ys(this.Jb(),!0),g.gg(function(){g.hv(this.Jb(),"iv-promo-inactive")},100,this),this.Jb().removeAttribute("aria-hidden"),this.isActive=!0,wmb(this),smb(this),tmb(this,this.K))};
g.k.hide=function(){this.isActive&&(g.fv(this.Jb(),"iv-promo-inactive"),this.isActive=!1,this.Jb().setAttribute("aria-hidden","true"))};
g.k.iL=function(a,b,c,d,e,f){return this.isCollapsed?!1:A4.prototype.iL.call(this,a,b,c,d,e,f)};
g.k.Z6=function(a){this.Z=!0;umb(this,500,a)};
g.k.Y6=function(){this.Z=!1;vmb(this)};
g.k.T6=function(a){a.stopPropagation();this.hide()};
g.k.U6=function(a){a.stopPropagation();wmb(this);this.isCollapsed=!0;g.fv(this.Jb(),"iv-promo-collapsed-no-delay");this.G.start()};
g.k.destroy=function(){this.G.dispose();A4.prototype.destroy.call(this)};g.w(ymb,g.YV);g.k=ymb.prototype;g.k.Fh=function(a,b){if(!Nmb(this.player.U().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.v2(b))&&Dmb(this,a),!0;case "removeCustomAnnotationById":return b&&this.j&&(amb(this.j,b),W3(this.player)),!0}return null};
g.k.getOptions=function(){return Nmb(this.player.U().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.Rt=function(){var a=this.player.U(),b=this.player.getVideoData(),c=a.annotationsLoadPolicy||b.annotationsLoadPolicy;return g.mU(b)||g.wU(this.player.app)?!1:1===c&&!b.tU||a.Na.get(b.videoId)||g.aU(b)||g.LSa(b)?!0:!1};
g.k.mJ=function(){if(this.C){var a=this.player.rb().getVideoContentRect(!0);g.ws(this.C.element,a.width,a.height);g.rs(this.C.element,a.left,a.top)}if(this.j){var b=this.player.qn();a=this.j;b=b.width;g.jv(a.D,"iv-drawer-small",426>=b);g.jv(a.D,"iv-drawer-big",1280<=b)}};
g.k.B1=function(a){Amb(this,a.state);g.mH(a.state,2)&&(this.Dk()&&this.Uo()&&2!==this.player.getPresentingPlayerType()&&this.WA(!1),this.VA(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.G=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.oC(h)&&h.responseXML?h.responseXML:null)&&(Dmb(b,h),g.fv(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.YV.prototype.load.call(this);Amb(this,this.player.Ub());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.BD()&&(a=Emb(this,a));var e={format:"XML",onFinish:a,onError:function(){b.G=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.U().Na.get(d);f&&Fmb(e,f);f=f&&(f.CM||f.MG);if(!c.gx||f)c.Xa?Bmb(this,c.Xa,e):(this.K=function(){if(!b.Z)b.onVideoDataChange(e);var h=b.player.getVideoData();(null==h?0:g.$T(h))&&!b.ma&&Jmb(b,h)},this.player.addEventListener("videodatachange",this.K));
g.LU(this.player,this.C.element,4);this.mJ();(f=g.aU(c))&&Imb(this,f);(f=g.LSa(c))&&f.featuredChannel&&Mmb(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null);this.Rg=g.af("ytp-cards-button",this.player.getRootNode());g.$T(c)&&Jmb(this,c)};
g.k.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Xa&&Bmb(this,b.Xa,a)};
g.k.unload=function(){this.player.yf("annotations_module");for(var a=g.u(Object.keys(this.N)),b=a.next();!b.done;b=a.next())this.N[b.value].destroy();this.W=null;this.j&&(this.j.destroy(),this.j=null,W3(this.player));this.Z=!1;this.G&&(this.G.abort(),this.G=null);this.ma=!1;this.N={};this.B.hide();g.YV.prototype.unload.call(this);this.C.detach();this.K&&(this.player.removeEventListener("videodatachange",this.K),this.K=null)};
g.k.eZ=function(a){a===this.player.getVideoData().videoId&&(this.loaded?Gmb(this):this.load())};
g.k.Dk=function(){var a;return(null==(a=this.j)?void 0:a.isAvailable())||this.ma};
g.k.Uo=function(){return!!this.j&&this.j.C};
g.k.WA=function(a,b,c){b=void 0===b?!1:b;this.Dk();this.j&&(a?c?t4(this.j,c,b):t4(this.j,"YOUTUBE_DRAWER_AUTO_OPEN",b):u4(this.j))};
g.k.VA=function(a,b){this.player.oa(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.xa=function(){this.player.U().Na.unsubscribe("vast_info_card_add",this.eZ,this);g.hv(this.player.getRootNode(),g.jZ.IV_DRAWER_OPEN);for(var a=this.ra,b=g.Lu,c=0,d=a.length;c<d;c++)b.Kj(a[c]);this.ra.length=0;g.YV.prototype.xa.call(this)};
g.k.createElement=function(a){a=new g.V(a);g.M(this,a);return a.element};g.XV("annotations_module",ymb);g.XV("creatorendscreen",tlb);})(_yt_player);
